packages:
  - packages/*

overrides:
  react: '^19.2.7'
  react-dom: '^19.2.7'
  '@tarojs/runner-utils>rollup': 4.60.3

allowBuilds:
  '@biomejs/biome': false
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: true

minimumReleaseAgeExclude:
  - '@weapp-tailwindcss/postcss@3.1.8'
  - weapp-tailwindcss@5.1.9
