import { combineLatest, concatMap, map, type Observable, shareReplay, take } from 'rxjs'
import type { Bootstrap, StartupEffects } from './types.ts'

/**
 * Creates the one bootstrap lifetime for a physical DevHost session.
 *
 * Output preparation happens before the DevEngine's initial output is consumed. Bootstrap publication then waits for the
 * first physical FullBuild and Vite's final listening endpoint, so hmr/info.js cannot advertise an address or project
 * state that DevTools cannot use yet. Errors intentionally remain on this observable's error channel because startup is
 * fatal.
 *
 * ```text
 * Vite listening endpoint ─┐
 *                           ├── bootstrap boundary ──> physical hmr/info.js + hmr/update.js
 * DevEngine baseline ──────┘                                      │
 *                                                                    └──> WX runtime may connect
 * ```
 */
export function createBootstrap$({
    buildId,
    initialEngineOutput$,
    listeningEndpoint$,
    prepareOutput$,
    writeBootstrap
}: StartupEffects & {
    /** Immutable identity generated by the DevHost edge for this physical session. */
    buildId: string
}): Observable<Bootstrap> {
    return prepareOutput$.pipe(
        take(1),
        concatMap(() =>
            combineLatest([initialEngineOutput$.pipe(take(1)), listeningEndpoint$.pipe(take(1))]).pipe(
                map(([, endpoint]) => ({ buildId, endpoint }))
            )
        ),
        concatMap((bootstrap) => writeBootstrap(bootstrap).pipe(map(() => bootstrap))),
        shareReplay({ bufferSize: 1, refCount: false })
    )
}
